version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "llevintza"
    assignees:
      - "llevintza"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    versioning-strategy: "auto"
    
    # Group updates by dependency type
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    
    # Ignore specific dependencies if needed
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "fastify"
        update-types: ["version-update:semver-major"]
      # Add other dependencies to ignore here if needed
    
    # Security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "llevintza"
    assignees:
      - "llevintza"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
      - "ci"
