cacheFolder: .yarn/cache

changesetBaseRefs:
  - main
  - master

checksumBehavior: update

enableGlobalCache: true

enableTelemetry: false

httpRetry: 3

httpTimeout: 60000

nodeLinker: node-modules

preferInteractive: true
