nodeLinker: node-modules

# Enable zero-installs (optional, can be disabled)
enableGlobalCache: true

# Package resolution settings
checksumBehavior: update

# Network settings
httpTimeout: 60000
httpRetry: 3

# Telemetry
enableTelemetry: false

# Yarn plugins
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# Cache settings
cacheFolder: .yarn/cache

# Install settings
preferInteractive: true

# Version control
changesetBaseRefs:
  - main
  - master
